"""init

Revision ID: 7610a9f03763
Revises: 
Create Date: 2025-04-05 12:42:22.104490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7610a9f03763'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_payers',
    sa.Column('tax_code', sa.String(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('id_number', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('license_issuer', sa.String(), nullable=True),
    sa.Column('rep_name', sa.String(), nullable=True),
    sa.Column('rep_address', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('tax_code', name=op.f('pk_tax_payers'))
    )
    op.create_index(op.f('ix_tax_payers_id_number'), 'tax_payers', ['id_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_payers_id_number'), table_name='tax_payers')
    op.drop_table('tax_payers')
    # ### end Alembic commands ###
